name = "my test theme"
# description
# license = 
# homepage = ""
min_version = ""
demo = ""

[extra]
[extra.ash]
top_section = "posts/"
# ash_links = [
# {url = "https://fireturtle.net", name = "test"},
# ]


categories = "categories"
tags = "tags"
# [extra.ash.translations.ja]
# asj_categories = "カテゴリ"
# ash_tags = "タグ"

[extra.ash.main]
font = "serif"
font_color = "white"
background_color = "black"

[extra.ash.sidebar]
font = "sans-serif"
font_color = "black"
background_color = "white"

[auther]
name = "fwtn"
homepage = "https://blog.fireturtle.net"
