name = "my test theme"
# description
# license = 
# homepage = ""
min_version = ""
demo = ""

[extra]
ash_top_section = "posts/"
# ash_links = [
# {url = "https://fireturtle.net", name = "test"},
# ]
ash_font.main = 
ash_font.sidebar

ash_categories = "categories"
ash_tags = "tags"
# [extra.translations.ja]
# asj_categories = "カテゴリ"
# ash_tags = "タグ"


[auther]
name = "fwtn"
homepage = "https://blog.fireturtle.net"
